name: client CI

on:
  push:
    branches:
      - main
      - client-dev
    paths:
      - "client/**"
  pull_request:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    name: test and build
    runs-on: self-hosted

    env:
      NODE_VERSION: "20"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: client

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: client

      - name: Lint and test
        run: |
          npm run lint
          echo "npm run test"
        working-directory: client

      - name: Build
        run: npm run build
        working-directory: client

  docker:
    name: Build and push
    if: ${{ github.ref == 'refs/heads/main' }}

    runs-on: self-hosted
    needs: [build]

    env:
      DOCKER_IMAGE_NAME: "devlinks-client"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:v${{ github.run_number }}
